Pause game
COMP350-Fall2022/ArtemisFission pull request #60
Opened 2022-11-02 21:30 UTC by johnavalos2

2022-11-03 00:49 UTC, jalexcrawford reviewed
Looks good! I think there might be a problem with how long we wait for game ticks, but I may have looked up the wrong tick function. See my other comment. :)

2022-11-03 00:49 UTC, jalexcrawford commented on Assets/Scripts/GameManager/GameController.cs
> +        }
With tick_threshold at 100,000. Wouldn't you only be able to pause the game for like 10 seconds before the contract controller logic locks up?

I'm doing the math in my head and powers of ten always mess me up though.

It might be good to just reset the base time in the contract controller when unpausing. It would also be good to have a small grace period for unpausing the game. Though that might get exploited by players. :P

2022-11-03 05:51 UTC, andrewcgraves commented on Assets/Scripts/GameManager/GameController.cs
> +        }
Nah in this case the globalTicks variable is independent and not really tied to anything at the moment. I added it in as a reminder to go back and have a tracker for the time

2022-11-03 05:52 UTC, andrewcgraves requested changes
I think it might be better to map the pause function to a toggleable hotkey for the time being. Maybe map it to SHIFT + P if that's possible?

2022-11-03 18:25 UTC, jalexcrawford commented
Good call Andrew! 

It looks like it'll pause on a left mouse click right now. Though spacebar might be more intuitive for pausing.

2022-11-04 02:26 UTC, Frances637 reviewed
I suggest that the pause function would pause the game until the player resumes their gameplay.

2022-11-04 04:00 UTC, merged