Added ResourceDisplay
COMP350-Fall2022/ArtemisFission pull request #74
Opened 2022-11-19 22:18 UTC by jalexcrawford

Added ResourceDisplay script that create a new Resources object with Money, Parts, and Morale set to 500,000, 0 and 0 respectively.

For every frame it will pull new data from the resources object and display it on the screen.

2022-11-21 01:02 UTC, johnavalos2 approved these changes

2022-11-21 17:58 UTC, Frances637 approved these changes
The resource display is very helpful for an individual employee's stats.

2022-11-21 21:42 UTC, andrewcgraves requested changes
Looks good! maybe just rename GetMorale to something like GetTotalMorale and check to see if the display changes were committed and in the right window

2022-11-28 02:17 UTC, jalexcrawford commented
Updated GetMorale to be GetTotalMorale and found that I needed to have the code in GameController in order to update it on the screen.

2022-11-30 02:39 UTC, closed without merging